## Googleドライブのマウント

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# ライブラリの準備

In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegressionCV
from sklearn.metrics import confusion_matrix
from sklearn.metrics import recall_score, accuracy_score
#from sklearn.decomposition import PCA

from sklearn.cluster import KMeans
from sklearn.neighbors import KNeighborsClassifier


import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

## sys.pathの設定

以下では，Googleドライブのマイドライブ直下にstudy_ai_mlフォルダを置くことを仮定しています．必要に応じて，パスを変更してください。

In [ ]:
# データの読み込み
cancer_df = pd.read_csv('/content/drive/My Drive/study_ai_ml_google/data/cancer.csv')

In [ ]:
print('cancer df shape: {}'.format(cancer_df.shape))

cancer df shape: (569, 33)


In [ ]:
# データの表示　　　569行　33列
cancer_df

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0      842302         M  ...                  0.11890          NaN
1      842517         M  ...                  0.08902          NaN
2    84300903         M  ...                  0.08758          NaN
3    84348301         M  ...                  0.17300          NaN
4    84358402         M  ...                  0.07678          NaN
..        ...       ...  ...                      ...          ...
564    926424         M  ...                  0.07115          NaN
565    926682         M  ...                  0.06637          NaN
566    926954         M  ...                  0.07820          NaN
567    927241         M  ...                  0.12400          NaN
568     92751         B  ...                  0.07039          NaN

[569 rows x 33 columns]

In [ ]:
# データ構造を確認
cancer_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [ ]:
# ‘Unnamed’列は欠損データのみのため削除　
cancer_df.drop('Unnamed: 32', axis=1, inplace=True)

・diagnosis: 診断結果 (良性がB / 悪性がM)
・説明変数は3列以降、目的変数を2列目としロジスティック回帰で分類

In [ ]:
# 目的変数の抽出
cancer_df['diag'] = cancer_df.diagnosis.apply(lambda d: 1 if d == 'M' else 0)
y = cancer_df['diag'] 

In [ ]:
# 説明変数の抽出    'radius_mean'から‘fractal_dimension_worst’までの３０列
X = cancer_df.loc[:, 'radius_mean':'fractal_dimension_worst']

In [ ]:
y

0      1
1      1
2      1
3      1
4      1
      ..
564    1
565    1
566    1
567    1
568    0
Name: diag, Length: 569, dtype: int64

In [ ]:
X

radius_mean  texture_mean  ...  symmetry_worst  fractal_dimension_worst
0          17.99         10.38  ...          0.4601                  0.11890
1          20.57         17.77  ...          0.2750                  0.08902
2          19.69         21.25  ...          0.3613                  0.08758
3          11.42         20.38  ...          0.6638                  0.17300
4          20.29         14.34  ...          0.2364                  0.07678
..           ...           ...  ...             ...                      ...
564        21.56         22.39  ...          0.2060                  0.07115
565        20.13         28.25  ...          0.2572                  0.06637
566        16.60         28.08  ...          0.2218                  0.07820
567        20.60         29.33  ...          0.4087                  0.12400
568         7.76         24.54  ...          0.2871                  0.07039

[569 rows x 30 columns]

In [ ]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 30 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   radius_mean              569 non-null    float64
 1   texture_mean             569 non-null    float64
 2   perimeter_mean           569 non-null    float64
 3   area_mean                569 non-null    float64
 4   smoothness_mean          569 non-null    float64
 5   compactness_mean         569 non-null    float64
 6   concavity_mean           569 non-null    float64
 7   concave points_mean      569 non-null    float64
 8   symmetry_mean            569 non-null    float64
 9   fractal_dimension_mean   569 non-null    float64
 10  radius_se                569 non-null    float64
 11  texture_se               569 non-null    float64
 12  perimeter_se             569 non-null    float64
 13  area_se                  569 non-null    float64
 14  smoothness_se            5

In [ ]:
# 学習用とテスト用でデータを分離
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

# 標準化
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

### ロジスティック回帰で学習

In [ ]:
# ロジスティック回帰で学習
#logistic = LogisticRegressionCV(cv=10, random_state=0)
logistic = LogisticRegressionCV(cv=10, random_state=0, max_iter=200)
logistic.fit(X_train_scaled, y_train)

# 検証
#print('Train score: {:.3f}'.format(logistic.score(X_train_scaled, y_train)))
#print('Test score: {:.3f}'.format(logistic.score(X_test_scaled, y_test)))
print('Confustion matrix:\n{}'.format(confusion_matrix(y_true=y_test, y_pred=logistic.predict(X_test_scaled))))

#                 Predicted
#                 Negative  Positive
#Actual Negative     TN        FP
#       Positive     FN        TP


# accuracy  正解率の算出
print('accuracy score:{:.4f}'.format( accuracy_score(y_true=y_test, y_pred=logistic.predict(X_test_scaled))))
# recall 再現率の算出
print('reacll score:{:.4f}'.format( recall_score(y_true=y_test, y_pred=logistic.predict(X_test_scaled))))

Confustion matrix:
[[89  1]
 [ 3 50]]
accuracy score:0.9720
reacll score:0.9434


   　※ロジスティクス回帰による分類予測　　　　正解率：　0.972　　再現率：　0.943


# k-近傍法による分類

In [ ]:
# k-NN モデルの生成
knc = KNeighborsClassifier(n_neighbors=5).fit(X_train, y_train)

In [ ]:
pred_knc_y = knc.predict(X_test)

In [ ]:
print('Confustion matrix:\n{}'.format(confusion_matrix(y_true=y_test, y_pred=pred_knc_y)))

#                 Predicted
#                 Negative  Positive
#Actual Negative     TN        FP
#       Positive     FN        TP

# accuracy  正解率の算出
print('accuracy score:{:.4f}'.format( accuracy_score(y_true=y_test, y_pred=pred_knc_y)))
# recall 再現率の算出
print('reacll score:{:.4f}'.format( recall_score(y_true=y_test, y_pred=pred_knc_y)))

Confustion matrix:
[[85  5]
 [ 4 49]]
accuracy score:0.9371
reacll score:0.9245


   　※k-近傍法による分類予測　　　　正解率：　0.937　　再現率：　0.925

  

# k-平均法による分類

In [ ]:
# k-means モデルの生成
model_KM = KMeans(n_clusters=2, random_state=0)

In [ ]:
model_KM.fit(X_train)
pred_kms_y = model_KM.predict(X_test)

In [ ]:
print('Confustion matrix:\n{}'.format(confusion_matrix(y_true=y_test, y_pred=pred_kms_y)))

#                 Predicted
#                 Negative  Positive
#Actual Negative     TN        FP
#       Positive     FN        TP


# accuracy  正解率の算出
print('accuracy score:{:.4f}'.format( accuracy_score(y_true=y_test, y_pred=pred_kms_y)))
# recall 再現率の算出
print('reacll score:{:.4f}'.format( recall_score(y_true=y_test, y_pred=pred_kms_y)))

Confustion matrix:
[[90  0]
 [22 31]]
accuracy score:0.8462
reacll score:0.5849


   　※k-平均法による分類予測　　　　正解率：　0.846　　再現率：　0.585

  